services:
  yomoji:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: prod
    container_name: yomoji
    ports:
      - "3001:3000"
      - "9231:9229"
    user: "1000"
    environment:
      - NODE_ENV=production
      - DEBUG=engine
    env_file:
      - ./.env
