services:
  yomoji:
    volumes:
      - ./:/app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    container_name: yomoji
    ports:
      - "3001:3000"
      - "9231:9229"
    environment:
      - NODE_ENV=development
      - DEBUG=engine
    env_file:
      - ./.env
